spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 2
  liquibase:
    enabled: false

venus:
  db:
    type: mysql
    database: star_blog_dev
    username: root
    password: 720428
    pool:
      enabled: true
      pool-type: druid

  logging:
    enabled: true
    level:
      com.ale.starblog.admin: debug
    log-file:
      info:
        file-path: star-blog-web/logs/info.log
      error:
        file-path: star-blog-web/logs/error.log

  security:
    token-type: redis
    token-expiration: 24h
    refresh-token-expiration-per-request: true
    permitted-uris:
      - uri: /auth/*
        methods:
          - all
