# 基础环境配置
services:
  postgres:
    image: postgres:17-alpine
    container_name: star-blog-postgres
    environment:
      POSTGRES_USER: postgres
      # 请自行配置env设置密码
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Shanghai
      LANG: zh_CN.utf8
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - star-blog-network

  minio:
    # 之后的版本大部分免费功能被砍了
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: star-blog-minio
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    restart: unless-stopped
    networks:
      - star-blog-network

  redis:
    image: redis:7-alpine
    container_name: star-blog-redis
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./redis-data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: unless-stopped
    networks:
      - star-blog-network

  nginx:
    image: nginx:1.28.0-alpine
    container_name: star-blog-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/ale-star-blog.cn.key:/etc/nginx/ssl/ale-star-blog.cn.key
      - ./nginx/ssl/ale-star-blog.cn.pem:/etc/nginx/ssl/ale-star-blog.cn.pem
      - ./nginx/html/admin/dist:/usr/share/nginx/html/star-blog/admin
    restart: unless-stopped
    networks:
      - star-blog-network
networks:
  star-blog-network: