# 业务模块配置
services:
  admin-service:
    image: star-blog-admin:latest
    container_name: star-blog-admin
    build:
      context: ./server/admin
      dockerfile: Dockerfile
    volumes:
      - ./server/admin/config:/home/star-blog-admin/config
      - ./server-logs/admin:/home/star-blog-admin/logs
    ports:
      - "9091:9091"
    networks:
      - star-blog-network
networks:
  star-blog-network: